# Generated by Django 2.2.16 on 2021-02-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0002_kb_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rt_systemtype_tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemtype_name', models.CharField(blank=True, db_column='SystemtypeName', max_length=64)),
                ('tool_id', models.ForeignKey(blank=True, db_column='ToolId', on_delete=django.db.models.deletion.CASCADE, to='my_blogs.Kb_tools')),
            ],
            options={
                'db_table': 'rt_systemtype_tool',
            },
        ),
    ]
