# Generated by Django 2.2.16 on 2021-02-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0003_rt_systemtype_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='rt_systemtype_tool',
            name='initstatus',
            field=models.BooleanField(blank=True, db_column='InitStatus', default=False),
        ),
    ]
