# Generated by Django 2.2.16 on 2021-04-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0004_rt_systemtype_tool_initstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kb_assents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assent_hostname', models.CharField(blank=True, db_column='AssentHostname', max_length=64)),
                ('assents_ip', models.CharField(blank=True, db_column='AssentsIp', max_length=64)),
                ('assent_mac', models.CharField(blank=True, db_column='AssentMac', max_length=64)),
                ('assent_os', models.CharField(blank=True, db_column='AssentOs', max_length=64)),
                ('assent_ports', models.TextField(blank=True, db_column='AssentPorts')),
            ],
            options={
                'db_table': 'kb_assents',
            },
        ),
        migrations.RemoveField(
            model_name='rt_systemtype_tool',
            name='tool_id',
        ),
        migrations.DeleteModel(
            name='Kb_tools',
        ),
        migrations.DeleteModel(
            name='Rt_systemtype_tool',
        ),
    ]
