# Generated by Django 2.2.16 on 2021-05-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blogs', '0006_blog_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_contents',
            name='BlogContents',
            field=models.TextField(blank=True, db_column='BlogContents', verbose_name='博客内容'),
        ),
    ]
