# Generated by Django 2.2.16 on 2020-12-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons_type', models.IntegerField(choices=[(1, '常规图标'), (2, '未定义2'), (3, '未定义3')], help_text='图标分类', verbose_name='类目级别')),
                ('name', models.CharField(default='', max_length=300, verbose_name='图标名')),
            ],
            options={
                'verbose_name': '图标',
                'verbose_name_plural': '图标',
            },
        ),
    ]
